version: '3.3'

# Usage:
#   wget -O - http://download1.graphhopper.com/public/photon-db-latest.tar.bz2 | pbzip2 -cd | tar x
#   chown -R 1000:1000 photon_data
#   docker-compose up

services:
  photon:
    image: photoprism/photon:latest
    ports:
      - 2322:2322 # [local port]:[container port]
    volumes:
      - "./photon_data:/home/photon/photon_data"
