// +build ignore

// This generates countries.go by running "go generate"
package main

import (
	"bufio"
	"encoding/json"
	"io/ioutil"
	"os"
	"strings"
	"text/template"
)

type Country struct {
	Code string
	Name string
}

var countries []Country

var reverse []Country

func main() {
	file, err := os.Open("countries_reverse.txt")
	defer file.Close()

	if err != nil {
		panic(err)
	}

	scanner := bufio.NewScanner(file)
	scanner.Split(bufio.ScanLines)

	for scanner.Scan() {
		parts := strings.Split(scanner.Text(), ":")

		if len(parts) < 2 {
			continue
		}

		reverse = append(reverse, Country{Code: strings.ToLower(parts[0]), Name: strings.ToLower(parts[1])})
	}

	rawData, err := ioutil.ReadFile("./countries.json")

	if err != nil {
		panic(err)
	}

	err = json.Unmarshal(rawData, &countries)

	if err != nil {
		panic(err)
	}

	f, err := os.Create("countries.go")

	if err != nil {
		panic(err)
	}

	defer f.Close()

	for i, v := range countries {
		countries[i].Code = strings.ToLower(v.Code)
	}

	packageTemplate.Execute(f, struct {
		Countries []Country
		Reverse   []Country
	}{
		Countries: countries,
		Reverse:   reverse,
	})
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
package maps

var CountryNames = map[string]string{
{{- range .Countries }}
	{{ printf "%q" .Code }}: {{ printf "%q" .Name }},
{{- end }}
}

var CountriesReverse = map[string]string{
{{- range .Reverse }}
	{{ printf "%q" .Name }}: {{ printf "%q" .Code }},
{{- end }}
}`))
